apiVersion: v1
kind: Template
labels:
  template: pinpoint-apm-ephemeral
message: Pinpoint APM Ephemeral
metadata:
  annotations:
    description: Pinpoint APM Ephemeral
    iconClass: icon-jenkins
    tags: pinpoint
  name: pinpoint-ephemeral-template
  namespace: openshift
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pinpoint
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "pinpoint"
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: pinpoint-apm
  spec:
    ports:
    - name: pinpoint
      port: 28080
      protocol: TCP
      targetPort: 28080
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: pinpoint-testapp
  spec:
    ports:
    - name: testapp
      port: 28081
      protocol: TCP
      targetPort: 28081
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: pinpoint-collector
  spec:
    ports:
    - name: pinpoint-tcp
      port: 9994
      protocol: TCP
      targetPort: 9994
    - name: pinpoint-udp1
      port: 9995
      protocol: UDP
      targetPort: 9995
    - name: pinpoint-udp12
      port: 9996
      protocol: UDP
      targetPort: 9996
    selector:
      app: pinpoint-apm
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: pinpoint-apm
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: pinpoint-apm
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: pinpoint-testapp
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: pinpoint-testapp
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "pinpoint"
  spec:
    triggers:
      - type: ConfigChange
      - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/makentenza/ocp-pinpoint-apm.git
    strategy:
      type: "Docker"
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "centos:7"
    output:
      to:
        kind: "ImageStreamTag"
        name: "pinpoint:latest"
- apiVersion: "v1"
  kind: DeploymentConfig
  metadata:
    name: "pinpoint-ephemeral"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: "pinpoint-ephemeral"
      spec:
        containers:
        - name: "pinpoint"
          image: "172.30.32.89:5000/pinpoint-apm/pinpoint"
        securityContext:
          privileged: true  
        serviceAccount: pinpoint
        serviceAccountName: pinpoint
    replicas: 1
    triggers:
      - type: "ConfigChange"
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - "pinpoint"
          from:
            kind: "ImageStreamTag"
            name: "pinpoint:latest"
    strategy:
      type: "Rolling"
    paused: false
    revisionHistoryLimit: 2
    minReadySeconds: 0
