apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2016-09-26T09:44:49Z
  generation: 2
  labels:
    compose: tmp
  name: pinpoint-hbase
  namespace: pinpoint
  resourceVersion: "1897"
  selfLink: /oapi/v1/namespaces/pinpoint/deploymentconfigs/pinpoint-hbase
  uid: de0a857f-83cd-11e6-8512-525400c583ad
spec:
  replicas: 1
  selector:
    deploymentconfig: pinpoint-hbase
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: pinpoint-hbase
    spec:
      containers:
      - image: naver/pinpoint-hbase:1.6.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: pinpoint-hbase
        ports:
        - containerPort: 2181
          protocol: TCP
        - containerPort: 16010
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pinpoint-hbase
      from:
        kind: ImageStreamTag
        name: pinpoint-hbase:1.6.0-SNAPSHOT
        namespace: pinpoint
    type: ImageChange
status:
  latestVersion: 1
  observedGeneration: 2
