apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2016-09-26T09:44:49Z
  generation: 2
  labels:
    compose: tmp
  name: pinpoint-web
  namespace: pinpoint
  resourceVersion: "1893"
  selfLink: /oapi/v1/namespaces/pinpoint/deploymentconfigs/pinpoint-web
  uid: de12357c-83cd-11e6-8512-525400c583ad
spec:
  replicas: 1
  selector:
    deploymentconfig: pinpoint-web
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: pinpoint-web
    spec:
      containers:
      - env:
        - name: ADMIN_PASSWORD
          value: admin123
        - name: CLUSTER_ENABLE
          value: "true"
        - name: CLUSTER_ZOOKEEPER_ADDRESS
          value: hbase
        - name: DISABLE_DEBUG
          value: "true"
        - name: HBASE_HOST
          value: hbase
        - name: HBASE_PORT
          value: "2181"
        - name: JDBC_DRIVER
          value: com.mysql.jdbc.Driver
        - name: JDBC_PASSWORD
          value: admin
        - name: JDBC_URL
          value: jdbc:mysql://mysql:3306/pinpoint?characterEncoding=UTF-8
        - name: JDBC_USERNAME
          value: admin
        image: naver/pinpoint-web:1.6.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: pinpoint-web
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pinpoint-web
      from:
        kind: ImageStreamTag
        name: pinpoint-web:1.6.0-SNAPSHOT
        namespace: pinpoint
    type: ImageChange
status:
  latestVersion: 1
  observedGeneration: 2
