apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2016-09-26T09:44:49Z
  generation: 2
  labels:
    compose: tmp
  name: pinpoint-collector
  namespace: pinpoint
  resourceVersion: "1889"
  selfLink: /oapi/v1/namespaces/pinpoint/deploymentconfigs/pinpoint-collector
  uid: de074ed2-83cd-11e6-8512-525400c583ad
spec:
  replicas: 1
  selector:
    deploymentconfig: pinpoint-collector
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: pinpoint-collector
    spec:
      containers:
      - env:
        - name: CLUSTER_ENABLE
          value: "true"
        - name: CLUSTER_ZOOKEEPER_ADDRESS
          value: hbase
        - name: COLLECTOR_TCP_PORT
          value: "9994"
        - name: COLLECTOR_UDP_SPAN_LISTEN_PORT
          value: "9996"
        - name: COLLECTOR_UDP_STAT_LISTEN_PORT
          value: "9995"
        - name: DISABLE_DEBUG
          value: "true"
        - name: HBASE_HOST
          value: hbase
        - name: HBASE_PORT
          value: "2181"
        image: naver/pinpoint-collector:1.6.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: pinpoint-collector
        ports:
        - containerPort: 9994
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pinpoint-collector
      from:
        kind: ImageStreamTag
        name: pinpoint-collector:1.6.0-SNAPSHOT
        namespace: pinpoint
    type: ImageChange
status:
  latestVersion: 1
  observedGeneration: 2
