apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2016-09-26T09:44:49Z
  generation: 3
  labels:
    compose: tmp
  name: pinpoint-mysql
  namespace: pinpoint
  resourceVersion: "2105"
  selfLink: /oapi/v1/namespaces/pinpoint/deploymentconfigs/pinpoint-mysql
  uid: de0e5936-83cd-11e6-8512-525400c583ad
spec:
  replicas: 1
  selector:
    deploymentconfig: pinpoint-mysql
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: pinpoint-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: pinpoint
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root123
        - name: MYSQL_USER
          value: admin
        image: mysql@sha256:966490bda4576655dc940923c4883db68cca0b3607920be5efff7514e0379aa7
        imagePullPolicy: IfNotPresent
        name: pinpoint-mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pinpoint-mysql
      from:
        kind: ImageStreamTag
        name: pinpoint-mysql:5.7
        namespace: pinpoint
      lastTriggeredImage: mysql@sha256:966490bda4576655dc940923c4883db68cca0b3607920be5efff7514e0379aa7
    type: ImageChange
status:
  details:
    causes:
    - imageTrigger:
        from:
          kind: ImageStreamTag
          name: pinpoint-mysql:5.7
          namespace: pinpoint
      type: ImageChange
    message: caused by an image change
  latestVersion: 1
  observedGeneration: 3
