apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-09-26T09:44:49Z
  labels:
    compose: tmp
  name: hbase
  namespace: pinpoint
  resourceVersion: "1234"
  selfLink: /api/v1/namespaces/pinpoint/services/hbase
  uid: de226451-83cd-11e6-8512-525400c583ad
spec:
  clusterIP: 172.30.24.167
  portalIP: 172.30.24.167
  ports:
  - name: 2181-tcp
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: 16010-tcp
    port: 16010
    protocol: TCP
    targetPort: 16010
  selector:
    deploymentconfig: pinpoint-hbase
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
