apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-09-26T09:44:50Z
  labels:
    compose: tmp
  name: mysql
  namespace: pinpoint
  resourceVersion: "1236"
  selfLink: /api/v1/namespaces/pinpoint/services/mysql
  uid: de2d5b03-83cd-11e6-8512-525400c583ad
spec:
  clusterIP: 172.30.180.154
  portalIP: 172.30.180.154
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deploymentconfig: pinpoint-mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
