apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-09-26T09:44:49Z
  labels:
    compose: tmp
  name: pinpoint-collector
  namespace: pinpoint
  resourceVersion: "1231"
  selfLink: /api/v1/namespaces/pinpoint/services/pinpoint-collector
  uid: de1574c6-83cd-11e6-8512-525400c583ad
spec:
  clusterIP: 172.30.21.220
  portalIP: 172.30.21.220
  ports:
  - name: 9994-tcp
    port: 9994
    protocol: TCP
    targetPort: 9994
  selector:
    deploymentconfig: pinpoint-collector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
