apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-09-26T09:44:50Z
  labels:
    compose: tmp
  name: pinpoint-web
  namespace: pinpoint
  resourceVersion: "1239"
  selfLink: /api/v1/namespaces/pinpoint/services/pinpoint-web
  uid: de3c7c0d-83cd-11e6-8512-525400c583ad
spec:
  clusterIP: 172.30.232.195
  portalIP: 172.30.232.195
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: pinpoint-web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
